leaders = {
    "brock": {
        "pokemon": {"geodude": [], "onix": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "misty": {
        "pokemon": {"starmie": [], "staryu": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "lt. surge": {
        "pokemon": {"raichu": [], "voltorb": [], "electrode": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "erika": {
        "pokemon": {"vileplume": [], "tangela": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "koga": {
        "pokemon": {"weezing": [], "muk": [], "koffing": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "sabrina": {
        "pokemon": {"alakazam": [], "mr. mime": [], "kadabra": [], "venomoth": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "blaine": {
        "pokemon": {"arcanine": [], "ponyta": [], "growlithe": [], "rapidash": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "giovanni": {
        "pokemon": {"rhyhorn": [], "nidoking": [], "nidoqueen": [], "dugtrio": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "lorelei": {
        "pokemon": {
            "dewgong": [],
            "cloyster": [],
            "jynx": [],
            "slowbro": [],
            "lapras": [],
        },
        "defense_score": 0,
        "attack_score": 0,
    },
    "bruno": {
        "pokemon": {"machamp": [], "onix": [], "hitmonlee": [], "hitmonchan": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "agatha": {
        "pokemon": {"gengar": [], "arbok": [], "golbat": [], "haunter": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "lance": {
        "pokemon": {"dragonite": [], "aerodactyl": [], "gyarados": [], "dragonair": []},
        "defense_score": 0,
        "attack_score": 0,
    },
    "champion green": {
        "pokemon": {
            "pidgeot": [],
            "alakazzam": [],
            "rhydon": [],
            "gyarados": [],
            "venusaur": [],
        },
        "defense_score": 0,
        "attack_score": 0,
    },
}

leader_pokemon = {
    "geodude": {"types": ["rock", "ground"]},
    "onix": {"types": ["rock", "ground"]},
    "starmie": {"types": ["water", "psychic"]},
    "staryu": {"types": ["water"]},
    "raichu": {"types": ["electric"]},
    "voltorb": {"types": ["electric"]},
    "electrode": {"types": ["electric"]},
    "vileplume": {"types": ["grass", "poison"]},
    "tangela": {"types": ["grass"]},
    "weezing": {"types": ["poison"]},
    "muk": {"types": ["poison"]},
    "koffing": {"types": ["poison"]},
    "alakazam": {"types": ["psychic"]},
    "mr. mime": {"types": ["psychic"]},
    "kadabra": {"types": ["psychic"]},
    "venomoth": {"types": ["bug", "poison"]},
    "arcanine": {"types": ["fire"]},
    "ponyta": {"types": ["fire"]},
    "growlithe": {"types": ["fire"]},
    "rapidash": {"types": ["fire"]},
    "rhyhorn": {"types": ["ground", "rock"]},
    "nidoking": {"types": ["poison", "ground"]},
    "nidoqueen": {"types": ["poison", "ground"]},
    "dugtrio": {"types": ["ground"]},
    "dewgong": {"types": ["water", "ice"]},
    "cloyster": {"types": ["water", "ice"]},
    "jynx": {"types": ["ice", "psychic"]},
    "slowbro": {"types": ["water", "psychic"]},
    "lapras": {"types": ["water", "ice"]},
    "machamp": {"types": ["fighting"]},
    "hitmonlee": {"types": ["fighting"]},
    "hitmonchan": {"types": ["fighting"]},
    "gengar": {"types": ["ghost", "poison"]},
    "arbok": {"types": ["poison"]},
    "golbat": {"types": ["poison", "flying"]},
    "haunter": {"types": ["ghost", "poison"]},
    "dragonite": {"types": ["dragon", "flying"]},
    "aerodactyl": {"types": ["rock", "flying"]},
    "gyarados": {"types": ["water", "flying"]},
    "dragonair": {"types": ["dragon"]},
    "pidgeot": {"types": ["normal", "flying"]},
    "alakazzam": {"types": ["psychic"]},
    "rhydon": {"types": ["ground", "rock"]},
    "venusaur": {"types": ["grass", "poison"]},
}

type_effectiveness = {
    "normal": {
        "strong_incoming": ["ghost"],
        "weak_incoming": ["fighting"],
        "strong_outgoing": [],
        "weak_outgoing": ["rock", "steel", "ghost"],
    },
    "fire": {
        "strong_incoming": ["fire", "grass", "ice", "bug", "steel", "fairy"],
        "weak_incoming": ["water", "ground", "rock"],
        "strong_outgoing": ["grass", "ice", "bug", "steel"],
        "weak_outgoing": ["fire", "water", "rock", "dragon"],
    },
    "water": {
        "strong_incoming": ["fire", "water", "ice", "steel"],
        "weak_incoming": ["electric", "grass"],
        "strong_outgoing": ["fire", "ground", "rock"],
        "weak_outgoing": ["water", "grass", "dragon"],
    },
    "electric": {
        "strong_incoming": ["electric", "flying", "steel"],
        "weak_incoming": ["ground"],
        "strong_outgoing": ["water", "flying"],
        "weak_outgoing": ["grass", "electric", "dragon", "ground"],
    },
    "grass": {
        "strong_incoming": ["water", "electric", "grass", "ground"],
        "weak_incoming": ["fire", "ice", "poison", "flying", "bug"],
        "strong_outgoing": ["water", "ground", "rock"],
        "weak_outgoing": [
            "fire",
            "grass",
            "poison",
            "flying",
            "bug",
            "dragon",
            "steel",
        ],
    },
    "poison": {
        "strong_incoming": ["grass", "fighting", "poison", "bug", "fairy"],
        "weak_incoming": ["ground", "psychic"],
        "strong_outgoing": ["grass", "fairy"],
        "weak_outgoing": ["poison", "ground", "rock", "ghost", "steel"],
    },
    "ice": {
        "strong_incoming": ["ice"],
        "weak_incoming": ["fire", "fighting", "rock", "steel"],
        "strong_outgoing": ["grass", "ground", "flying", "dragon"],
        "weak_outgoing": ["fire", "water", "ice", "steel"],
    },
    "fighting": {
        "strong_incoming": ["bug", "rock", "dark"],
        "weak_incoming": ["flying", "psychic", "fairy"],
        "strong_outgoing": ["normal", "ice", "rock", "dark", "steel"],
        "weak_outgoing": ["flying", "poison", "bug", "psychic", "fairy", "ghost"],
    },
    "ground": {
        "strong_incoming": ["poison", "rock", "electric"],
        "weak_incoming": ["water", "grass", "ice"],
        "strong_outgoing": ["fire", "electric", "poison", "rock", "steel"],
        "weak_outgoing": ["grass", "bug", "flying"],
    },
    "flying": {
        "strong_incoming": ["grass", "fighting", "ground", "bug"],
        "weak_incoming": ["electric", "ice", "rock"],
        "strong_outgoing": ["grass", "fighting", "bug"],
        "weak_outgoing": ["electric", "rock", "steel"],
    },
    "psychic": {
        "strong_incoming": ["fighting", "psychic"],
        "weak_incoming": ["bug", "ghost", "dark"],
        "strong_outgoing": ["fighting", "poison"],
        "weak_outgoing": ["psychic", "steel", "dark"],
    },
    "bug": {
        "strong_incoming": ["grass", "fighting", "ground"],
        "weak_incoming": ["fire", "flying", "rock"],
        "strong_outgoing": ["grass", "psychic", "dark"],
        "weak_outgoing": [
            "fire",
            "fighting",
            "poison",
            "flying",
            "ghost",
            "steel",
            "fairy",
        ],
    },
    "rock": {
        "strong_incoming": ["normal", "fire", "poison", "flying"],
        "weak_incoming": ["water", "grass", "fighting", "ground", "steel"],
        "strong_outgoing": ["fire", "ice", "flying", "bug"],
        "weak_outgoing": ["fighting", "ground", "steel"],
    },
    "ghost": {
        "strong_incoming": ["normal", "fighting", "poison", "bug"],
        "weak_incoming": ["ghost", "dark"],
        "strong_outgoing": ["psychic", "ghost"],
        "weak_outgoing": ["dark", "normal"],
    },
    "dragon": {
        "strong_incoming": ["fire", "water", "electric", "grass"],
        "weak_incoming": ["ice", "dragon", "fairy"],
        "strong_outgoing": ["dragon"],
        "weak_outgoing": ["steel", "fairy"],
    },
    "dark": {
        "strong_incoming": ["ghost", "dark", "psychic"],
        "weak_incoming": ["fighting", "bug", "fairy"],
        "strong_outgoing": ["psychic", "ghost"],
        "weak_outgoing": ["fighting", "dark", "fairy"],
    },
    "steel": {
        "strong_incoming": [
            "normal",
            "grass",
            "ice",
            "flying",
            "psychic",
            "bug",
            "rock",
            "dragon",
            "steel",
            "fairy",
        ],
        "weak_incoming": ["fire", "fighting", "ground"],
        "strong_outgoing": ["ice", "rock", "fairy"],
        "weak_outgoing": ["fire", "water", "electric", "steel"],
    },
    "fairy": {
        "strong_incoming": ["fighting", "bug", "dark", "dragon"],
        "weak_incoming": ["poison", "steel"],
        "strong_outgoing": ["fighting", "dragon", "dark"],
        "weak_outgoing": ["fire", "poison", "steel"],
    },
}
